services:
  - type: web
    name: ajali-backend
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn server.app:create_app()"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ajali-db
          property: connectionString
      - key: FLASK_ENV
        value: production
databases:
  - name: ajali-db
